Repository badges/shields, pull requests merged in 2018-08, with the labels that each got.

#1808 Split front end into one page per category
  frontend/components/badge-examples.js
  frontend/components/examples-page.js
  frontend/components/header.js
  frontend/components/meta.js
  frontend/components/search-results.js
  frontend/constants.js
  package-lock.json
  package.json
  pages/index.js
Labels: frontend, performance-improvement

#1797 Tweak layout of services to conveniently handle large service families [appveyor cdnjs clojars gem npm]
  dangerfile.js
  services/apm/apm.service.js
  services/appveyor/appveyor.service.js
  services/cdnjs/cdnjs.service.js
  services/clojars/clojars.service.js
  services/gem/gem.service.js
  services/index.js
  services/npm/npm-type-definitions.service.js
  services/time/time.service.js
Labels: core

#1810 Add support for simple-icons, colored icons with ?logoColor
  __snapshots__/make-badge.spec.js
  frontend/components/usage.js
  lib/badge-data.js
  lib/badge-data.spec.js
  lib/load-logos.js
  lib/load-simple-icons.js
  lib/logo-helper.js
  lib/logo-helper.spec.js
  lib/make-badge.spec.js
  lib/request-handler.js
  package-lock.json
  package.json
Labels: core

#1813 Start cleaning up github auth routes
  lib/github-auth.js
  server.js
  services/github/auth/admin.js
Labels: core

#1833 Update several lockfile dependencies using `npm audit fix`
  package-lock.json
  package.json
Labels: dependencies

#1840 upgrade react and related dependencies
  package-lock.json
  package.json
Labels: dependencies

#1843 don't run danger on dependabot PRs
  .circleci/config.yml
Labels: developer-experience

#1846 Increased default BADGE_MAX_AGE_SECONDS
  frontend/components/usage.js
  lib/request-handler.js
  lib/request-handler.spec.js
Labels: performance-improvement

#1812 GithubApiProvider: injectible interface for code that calls [github] (also affects [suggest php-eye travis])
  .circleci/config.yml
  lib/github-provider.js
  lib/php-version.js
  lib/suggest.js
  package.json
  server.js
  services/github/github-api-provider.integration.js
  services/github/github-api-provider.js
  services/github/github-api-provider.spec.js
Labels: core

#1859 Show test status on master, not latest build
  README.md
Labels: developer-experience

#1816 [GitHub] Fix undefined badges
  lib/github-helpers.js
  lib/github-helpers.spec.js
  server.js
  services/github/github.tester.js
Labels: bug, service-badge

#1743 [RFC] Add Joi-based request validation to BaseJsonService and rewrite [NPM] and [node] badges; also affects [apm appveyor cdnjs clojars gem]
  lib/all-badge-examples.js
  lib/npm-badge-helpers.js
  lib/npm-badge-helpers.spec.js
  lib/npm-provider.js
  package-lock.json
  package.json
  server.js
  services/apm/apm.service.js
  services/appveyor/appveyor.service.js
  services/base-json.spec.js
  services/base.js
  services/base.spec.js
  services/cdnjs/cdnjs.service.js
  services/clojars/clojars.service.js
  services/gem/gem.service.js
  services/node/node-version-color.js
  services/node/node.service.js
  services/node/node.tester.js
  services/npm/npm-base.js
  services/npm/npm-downloads.service.js
  services/npm/npm-license.service.js
  services/npm/npm-type-definitions.service.js
  services/npm/npm-type-definitions.spec.js
  services/npm/npm-version.service.js
  services/npm/npm.tester.js
Labels: core

#1167 Turn on prettier (except repo root)
  .circleci/config.yml
  .eslintrc-preferred.yml
  .prettierignore
  .prettierrc.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: developer-experience

#1885 Lengthen timeout on a flaky service test
  services/github/github.tester.js
Labels: developer-experience

#1883 Validate response json in [apm appveyor cdnjs clojars gem] also affects [npm]
  services/apm/apm.service.js
  services/appveyor/appveyor.service.js
  services/cdnjs/cdnjs.service.js
  services/clojars/clojars.service.js
  services/gem/gem-downloads.service.js
  services/gem/gem-owner.service.js
  services/gem/gem-rank.service.js
  services/gem/gem-version.service.js
  services/gem/gem.service.js
  services/npm/npm-downloads.service.js
  services/validators.js
Labels: service-badge

#1884 BaseService: Make it easier to add more config options; tested on [dynamic-json]
  services/base.js
Labels: core

#1896 support for colorA + logo
  templates/flat-square-template.svg
  templates/flat-template.svg
  templates/for-the-badge-template.svg
  templates/plastic-template.svg
  templates/popout-square-template.svg
  templates/popout-template.svg
Labels: core

#1889 Split BaseService and BaseJsonService into separate modules; tested on [clojars gem npm appveyor cdnjs]
  services/apm/apm.service.js
  services/appveyor/appveyor.service.js
  services/base-json.js
  services/base-json.spec.js
  services/base.js
  services/base.spec.js
  services/cdnjs/cdnjs.service.js
  services/clojars/clojars.service.js
  services/gem/gem-downloads.service.js
  services/gem/gem-owner.service.js
  services/gem/gem-rank.service.js
  services/gem/gem-version.service.js
  services/npm/npm-base.js
  services/npm/npm-downloads.service.js
  services/time/time.service.js
Labels: core

#1890 Add InvalidParameter runtime error and return inaccessible for 5xx errors
  lib/error-helper.js
  lib/error-helper.spec.js
  services/base.js
  services/base.spec.js
  services/errors.js
Labels: core

#1886 Fix and test the github admin route
  lib/github-auth.js
  lib/sys/secret-is-valid.js
  services/github/auth/admin.js
  services/github/auth/admin.spec.js
Labels: bug, core

#1863 Refactor and test [github] token persistence
  lib/github-auth.js
  lib/in-process-server-test-helpers.js
  lib/service-test-runner/cli.js
  lib/text-formatters.spec.js
  lib/token-persistence.js
  lib/token-persistence.spec.js
  package-lock.json
  package.json
  server.js
  services/github/github-constellation.js
Labels: core

#1893 ServiceTester: Minor readability tweak; test on [dynamic-json]
  services/service-tester.js
Labels: core

#1903 Create Monitoring category
  lib/all-badge-examples.js
Labels: service-badge

#1895 Add badge for dependents and dependent repos using Libraries.io [librariesio-dependents librariesio-dependent-repos]
  services/base-json.js
  services/librariesio/librariesio-base.js
  services/librariesio/librariesio-dependent-repos.service.js
  services/librariesio/librariesio-dependent-repos.tester.js
  services/librariesio/librariesio-dependents.service.js
  services/librariesio/librariesio-dependents.tester.js
  services/npm/npm-base.js
Labels: service-badge

#1898 Add [librariesio-sourcerank]
  services/librariesio/librariesio-base.js
  services/librariesio/librariesio-sourcerank.service.js
  services/librariesio/librariesio-sourcerank.tester.js
  services/validators.js
Labels: service-badge

#1901 use fetch/render pattern in [apm appveyor cdnjs clojars gem]
  services/apm/apm.service.js
  services/apm/apm.tester.js
  services/appveyor/appveyor.service.js
  services/cdnjs/cdnjs.service.js
  services/cdnjs/cdnjs.tester.js
  services/clojars/clojars.service.js
  services/clojars/clojars.tester.js
  services/gem/gem-downloads.service.js
  services/gem/gem-owner.service.js
  services/gem/gem-rank.service.js
  services/gem/gem-version.service.js
  services/gem/gem.tester.js
Labels: service-badge

#1904 Fix an edge case in NpmBase
  services/npm/npm-base.js
  services/npm/npm.tester.js
Labels: bug, service-badge

#1900 Clean up our callback style and enforce no exclusive tests [gem gemnasium dynamic-json dynamic-xml]
  .eslintrc-preferred.yml
  .eslintrc.yml
  frontend/components/search-results.js
  lib/analytics.js
  lib/github-auth.js
  lib/github-provider.js
  lib/licenses.spec.js
  lib/load-logos.js
  lib/load-simple-icons.js
  lib/log.js
  lib/log.spec.js
  lib/luarocks-version.js
  lib/make-badge.js
  lib/make-badge.spec.js
  lib/nuget-provider.js
  lib/pypi-helpers.js
  lib/pypi-helpers.spec.js
  lib/request-handler.js
  lib/suggest.js
  lib/svg-badge-parser.js
  lib/sys/monitor.js
  lib/teamcity-badge-helpers.js
  lib/text-formatters.js
  lib/text-measurer.spec.js
  lib/version.js
  package-lock.json
  package.json
  services/base-json.spec.js
  services/base.spec.js
  services/gem/gem-downloads.service.js
  services/gemnasium/gemnasium.tester.js
  services/github/auth/admin.js
  services/json/json.tester.js
  services/service-tester.js
  services/xml/xml.tester.js
Labels: developer-experience

#1891 Rewrite [uptimerobot]
  lib/all-badge-examples.js
  server.js
  services/uptimerobot/uptimerobot-base.js
  services/uptimerobot/uptimerobot-ratio.service.js
  services/uptimerobot/uptimerobot-status.service.js
  services/uptimerobot/uptimerobot.tester.js
Labels: service-badge

#1888 [GitHub] Error message customisation for all status codes
  lib/error-helper.js
  lib/error-helper.spec.js
  lib/github-helpers.js
  lib/github-helpers.spec.js
  server.js
  services/apm/apm.service.js
  services/appveyor/appveyor.service.js
  services/base-json.js
  services/github/github.tester.js
  services/npm/npm-base.js
  services/npm/npm-downloads.service.js
  services/npm/npm-version.service.js
Labels: core

#1926 Prevent merging exclusive service tests
  dangerfile.js
  package-lock.json
  package.json
  services/npm/npm.tester.js
Labels: developer-experience

#1930 Avoid warning during linting
  .eslintrc-frontend.yml
Labels: developer-experience

#1935 Example command for starting server with SENTRY_DSN after sudo
  doc/self-hosting.md
Labels: self-hosting

#1938 Disable CircleCI cache
  .circleci/config.yml
Labels: developer-experience

#1929 Service logging tweaks
  services/base-json.js
  services/base.js
  services/base.spec.js
  services/service-tester.js
  services/trace.js
Labels: developer-experience

#1944 Fix and test trace logging in BaseJsonService
  services/base-json.js
  services/base-json.spec.js
Labels: bug, core

#1906 Refactor [github] token persistence, again
  lib/github-auth.js
  lib/token-persistence.js
  lib/token-persistence.spec.js
  package-lock.json
  package.json
  services/github/github-constellation.js
Labels: core

#1933 Run tests by prefix e.g. [librariesio]
  lib/service-test-runner/runner.js
  lib/service-test-runner/services-for-title.js
  lib/service-test-runner/services-for-title.spec.js
Labels: developer-experience

#1897 Change format of [npm] type definitions badge
  services/npm/npm-base.js
  services/npm/npm-type-definitions.service.js
  services/npm/npm-type-definitions.spec.js
  services/npm/npm.tester.js
Labels: service-badge

#1939 Optionally persist [Github] tokens in Redis
  .circleci/config.yml
  CONTRIBUTING.md
  Makefile
  doc/self-hosting.md
  lib/fs-token-persistence.js
  lib/fs-token-persistence.spec.js
  lib/redis-token-persistence.integration.js
  lib/redis-token-persistence.js
  lib/server-config.js
  lib/token-persistence.js
  package-lock.json
  package.json
  services/github/github-constellation.js
Labels: core

#1945 Sort some badges
  lib/all-badge-examples.js
  services/gem/gem-rank.service.js
  services/node/node.service.js
  services/npm/npm-version.service.js
Labels: frontend

#1940 Rewrite [appveyor] tests badge
  lib/all-badge-examples.js
  server.js
  services/appveyor/appveyor-base.js
  services/appveyor/appveyor-ci.service.js
  services/appveyor/appveyor-tests.service.js
  services/appveyor/appveyor.service.js
Labels: service-badge

#1924 don't run deploy bot on dependabot PRs
  .github/probot.js
Labels: developer-experience

#1931 Allow migrating legacy services to services/ affects [continuousphp shippable]
  lib/all-badge-examples.js
  server.js
  services/continuousphp/continuousphp.service.js
  services/legacy-service.js
  services/shippable/shippable.service.js
Labels: core, service-badge

#1948 Sort some more badges
  lib/all-badge-examples.js
  services/node/node.service.js
  services/npm/npm-type-definitions.service.js
Labels: frontend

#1934 Reduce boilerplate for creating new testers [npm appveyor gem uptimerobot clojars]
  package-lock.json
  package.json
  services/appveyor/appveyor-ci.tester.js
  services/appveyor/appveyor-tests.tester.js
  services/appveyor/appveyor.tester.js
  services/clojars/clojars-version.service.js
  services/clojars/clojars-version.tester.js
  services/create-service-tester.js
  services/gem/gem-downloads.tester.js
  services/gem/gem-owner.tester.js
  services/gem/gem-rank.tester.js
  services/gem/gem-version.tester.js
  services/librariesio/librariesio-dependent-repos.tester.js
  services/librariesio/librariesio-dependents.tester.js
  services/librariesio/librariesio-sourcerank.tester.js
  services/npm/npm-downloads.tester.js
  services/npm/npm-license.tester.js
  services/npm/npm-type-definitions.tester.js
  services/npm/npm-version.tester.js
  services/npm/npm.tester.js
  services/service-tester.js
  services/uptimerobot/uptimerobot-ratio.tester.js
  services/uptimerobot/uptimerobot-status.tester.js
  services/uptimerobot/uptimerobot.tester.js
Labels: developer-experience

#1964 [librariesio] Fixed error handling
  services/librariesio/librariesio-base.js
Labels: bug, service-badge

#1970 danger: help users to write server tests
  dangerfile.js
Labels: developer-experience

#1973 Clarify what is used to run the specific tests
  doc/service-tests.md
Labels: developer-experience

#1974 make wercker preview badge static
  services/wercker/wercker.service.js
Labels: performance-improvement, service-badge

#1928 danger: highlight service in msg
  dangerfile.js
Labels: developer-experience

#1922 Rewrite [pypi]; affects [npm]
  lib/all-badge-examples.js
  lib/deprecation-helpers.js
  lib/licenses.js
  lib/licenses.spec.js
  lib/version.js
  lib/version.spec.js
  server.js
  services/base.js
  services/deprecated-service.js
  services/errors.js
  services/npm/npm-license.service.js
  services/npm/npm-version.service.js
  services/pypi/pypi-base.js
  services/pypi/pypi-djversions.service.js
  services/pypi/pypi-downloads.service.js
  services/pypi/pypi-format.service.js
  services/pypi/pypi-helpers.js
  services/pypi/pypi-helpers.spec.js
  services/pypi/pypi-implementation.service.js
  services/pypi/pypi-license.service.js
  services/pypi/pypi-pyversions.service.js
  services/pypi/pypi-status.service.js
  services/pypi/pypi-version.service.js
  services/pypi/pypi-wheel.service.js
  services/pypi/pypi.tester.js
Labels: service-badge

#1957 Reduce boilerplate in a few more service testers [cdnjs continuousphp node shippable wercker gem]
  services/cdnjs/cdnjs.tester.js
  services/continuousphp/continuousphp.service.js
  services/continuousphp/continuousphp.tester.js
  services/gem/gem-downloads.tester.js
  services/node/node.tester.js
  services/shippable/shippable.tester.js
  services/wercker/wercker.tester.js
Labels: service-badge

#1986 [elm-package] Fix elm package service
  services/elm-package/elm-package.service.js
  services/elm-package/elm-package.tester.js
Labels: bug, service-badge

#1927 refactor [circleci] integration
  lib/all-badge-examples.js
  server.js
  services/circleci/circleci.service.js
  services/circleci/circleci.tester.js
Labels: service-badge

#1989 Use Joi 13.6.0 on the servers
  package.json
Labels: bug, dependencies, operations

#1996 Improved deployment bot message
  .github/probot.js
Labels: developer-experience, operations

#1998 Use render helpers in existing new-style services [apm cdnjs gemversion]
  services/apm/apm.service.js
  services/cdnjs/cdnjs.service.js
  services/gem/gem-version.service.js
Labels: service-badge

#2020 update logo submission docs
  CONTRIBUTING.md
Labels: documentation

#2019 update contributing guidance
  CONTRIBUTING.md
  README.md
Labels: documentation

#2007 Combined update of eslint dependencies
  frontend/components/usage.js
  frontend/lib/badge-url.spec.js
  package-lock.json
  package.json
Labels: dependencies

#2018 Rewrite deprecated services and add tests [bithound cauditor dotnetstatus gemnasium gratipay magnumci snap-ci versioneye]
  lib/all-badge-examples.js
  lib/deprecation-helpers.js
  lib/deprecation-helpers.spec.js
  services/base.js
  services/base.spec.js
  services/bithound/bithound.service.js
  services/cauditor/cauditor.service.js
  services/dotnetstatus/dotnetstatus.service.js
  services/gemnasium/gemnasium.service.js
  services/gemnasium/gemnasium.tester.js
  services/gratipay/gratipay.service.js
  services/magnumci/magnumci.service.js
  services/snap-ci/snap-ci.service.js
  services/snap-ci/snap-ci.tester.js
  services/versioneye/versioneye.service.js
Labels: core, service-badge

#2023 [pypi]: Fix broken badges
  services/pypi/pypi-base.js
  services/pypi/pypi-helpers.js
  services/pypi/pypi-helpers.spec.js
  services/pypi/pypi-license.service.js
  services/pypi/pypi.tester.js
Labels: bug, service-badge

#2013 danger bot msg: cleaner look
  dangerfile.js
Labels: developer-experience

#1965 new badge: f-droid
  services/base-http.js
  services/base-json.js
  services/base.js
  services/base.spec.js
  services/f-droid/f-droid.service.js
  services/f-droid/f-droid.tester.js
Labels: service-badge
