Repository badges/shields, pull requests merged in 2018-05, with the labels that each got.

#1681 Add grade badge for [lgtm]
  lib/all-badge-examples.js
  server.js
  services/lgtm/lgtm.tester.js
Labels: service-badge

#1683 [cdnjs gem] make exception classes more consistent
  lib/error-helper.js
  lib/request-handler.js
  services/errors.js
  services/gem/gem.js
Labels: core

#1684 [homebrew] Adapt to new JSON API of formulae.brew.sh
  server.js
  services/homebrew/homebrew.tester.js
Labels: service-badge

#1695 update request
  package-lock.json
  package.json
Labels: greenkeeper

#1697 upgrade sinon
  package-lock.json
  package.json
Labels: greenkeeper

#1686 Ensure both docker CMDs are invoked
  Dockerfile
Labels: self-hosting

#1703 add more rules to dangerfile
  dangerfile.js
  package-lock.json
  package.json
Labels: developer-experience
