Repository badges/shields, pull requests merged in 2020-08, with the labels that each got.

#5388 VS Code Marketplace Last Updated Badge added along with tests, run [VisualStudioMarketplace]
  services/visual-studio-marketplace/visual-studio-marketplace-azure-devops-installs.tester.js
  services/visual-studio-marketplace/visual-studio-marketplace-base.js
  services/visual-studio-marketplace/visual-studio-marketplace-downloads.tester.js
  services/visual-studio-marketplace/visual-studio-marketplace-last-updated.service.js
  services/visual-studio-marketplace/visual-studio-marketplace-last-updated.tester.js
  services/visual-studio-marketplace/visual-studio-marketplace-rating.tester.js
  services/visual-studio-marketplace/visual-studio-marketplace-release-date.service.js
  services/visual-studio-marketplace/visual-studio-marketplace-release-date.tester.js
  services/visual-studio-marketplace/visual-studio-marketplace-version.tester.js
Labels: service-badge, squash when passing

#5391 Changed [LGTM] Alerts Badge
  services/lgtm/lgtm-alerts.service.js
  services/lgtm/lgtm-alerts.tester.js
Labels: service-badge, squash when passing

#5393 add guidance about scraping and unofficial APIs
  CONTRIBUTING.md
Labels: documentation

#5262 [GitlabCoverage] Add badge for code coverage
  services/gitlab/gitlab-coverage.service.js
  services/gitlab/gitlab-coverage.tester.js
Labels: service-badge, squash when passing

#5394 Fix all remaining LGTM alerts
  frontend/lib/generate-image-markup.ts
  gatsby-browser.js
  services/codecov/codecov.tester.js
Labels: developer-experience

#5410 Update Node.js versions in README
  README.md
Labels: documentation

#5370 Add quickstart section to readme
  README.md
Labels: documentation

#5316 [Bintray] Downloads (Bintray Versions renamed and not changed)
  package-lock.json
  services/bintray/bintray-downloads.service.js
  services/bintray/bintray-downloads.spec.js
  services/bintray/bintray-downloads.tester.js
  services/bintray/bintray-version.service.js
  services/bintray/bintray-version.spec.js
  services/bintray/bintray-version.tester.js
Labels: service-badge, squash when passing

#5416 Migrate to the official [F-Droid] API
  services/f-droid/f-droid.service.js
  services/f-droid/f-droid.tester.js
Labels: service-badge, squash when passing

#5432 auto-close 'version bump only' gatsby deps
  .github/workflows/auto-approve.yml
Labels: dependencies, squash when passing

#5436 Run on node 12 in production, update test matrix
  .circleci/config.yml
  Dockerfile
  README.md
  doc/TUTORIAL.md
  doc/self-hosting.md
  now.json
  package.json
Labels: dependencies, operations

#5440 Adopt static fields in [amo] and core
  core/base-service/base-graphql.spec.js
  core/base-service/base-json.spec.js
  core/base-service/base-svg-scraping.spec.js
  core/base-service/base-xml.spec.js
  core/base-service/base-yaml.spec.js
  core/base-service/base.js
  core/base-service/base.spec.js
  core/base-service/deprecated-service.js
  core/base-service/loader-test-fixtures/valid-array.fixture.js
  core/base-service/loader-test-fixtures/valid-class.fixture.js
  core/base-service/loader-test-fixtures/valid-object.fixture.js
  core/base-service/redirector.js
  doc/TUTORIAL.md
  doc/rewriting-services.md
  services/amo/amo-base.js
  services/amo/amo-downloads.service.js
  services/amo/amo-rating.service.js
  services/amo/amo-users.service.js
  services/amo/amo-version.service.js
Labels: core, service-badge

#5442 [GithubWorkflowStatus] add event query string parameter
  services/github/github-workflow-status.service.js
  services/github/github-workflow-status.tester.js
Labels: service-badge, squash when passing

#5456 Remove badgerbadgerbadger from related projects and add poser
  README.md
Labels: documentation

#5468 Update documentation about snapshot tests
  README.md
Labels: documentation
