Repository badges/shields, pull requests merged in 2020-05, with the labels that each got.

#4984 [dynamicjson] Fix unexpected token in JSONPath query
  services/dynamic/dynamic-json.tester.js
  services/dynamic/json-path.js
Labels: bug, service-badge

#4985 Allow a numeric version for NuGet v2 [chocolatey powershellgallery resharper]
  services/nuget/nuget-v2-service-family.js
Labels: bug, service-badge

#4987 Fill GitHub token pool on startup
  core/server/server.js
Labels: core

#4983 Fix production crash in [GithubStars] with trailing spaces
  services/github/github-stars.service.js
  services/github/github-stars.tester.js
Labels: bug, service-badge, squash when passing

#4991 fix link width params
  __snapshots__/make-badge.spec.js
  badge-maker/lib/badge-renderers.js
Labels: npm-package, squash when passing

#5009 re-enable dependabot node10+ upgrades
  .dependabot/config.yml
Labels: dependencies, squash when passing

#5008 upgrade to got 11; test on [github]
  core/base-service/legacy-request-handler.spec.js
  core/service-test-runner/pull-request-services-cli.js
  package-lock.json
  package.json
  scripts/badge-cli.js
  services/github/auth/acceptor.spec.js
  services/github/auth/admin.spec.js
  services/suggest.integration.js
  services/suggest.spec.js
Labels: dependencies, squash when passing

#5010 require node 10+ in badge-maker package.json
  badge-maker/package.json
Labels: npm-package

#5044 run typescript checks in `npm test`
  package.json
Labels: developer-experience

#5045 show link previews on /dev/styles page
  core/badge-urls/make-badge-url.d.ts
  core/badge-urls/make-badge-url.js
  frontend/components/common.tsx
  frontend/components/development/style-page.tsx
Labels: frontend

#5013 update production hosting/deploy docs
  doc/production-hosting.md
Labels: documentation

#5040 Add badge for [PackagistStars] (favers)
  services/packagist/packagist-stars.service.js
  services/packagist/packagist-stars.tester.js
Labels: service-badge

#5041 Streamline Packagist Badge Titles
  services/packagist/packagist-downloads.service.js
  services/packagist/packagist-license.service.js
  services/packagist/packagist-php-version.service.js
Labels: squash when passing

#5047 increase timeout on unique service names test
  services/check-services.spec.js
Labels: squash when passing

#5049 fix Gitlab service tests
  services/gitlab/gitlab-pipeline-status.service.js
  services/gitlab/gitlab-pipeline-status.tester.js
Labels: keep-service-tests-green, squash when passing

#5050 increase timeout for service name check (again)
  services/check-services.spec.js
Labels: squash when passing

#4968 Support [Codecov] coverage badge with flag
  services/codecov/codecov.service.js
  services/codecov/codecov.spec.js
  services/codecov/codecov.tester.js
Labels: service-badge, squash when passing

#5038 Fix rendering in Firefox on Windows
  __snapshots__/make-badge.spec.js
  badge-maker/lib/badge-renderers.js
Labels: npm-package

#5046 send s-maxage and public cache headers
  core/base-service/cache-headers.js
  core/base-service/cache-headers.spec.js
  core/base-service/legacy-request-handler.spec.js
Labels: performance-improvement, squash when passing

#5037 v3 stable
  badge-maker/lib/index.js
  badge-maker/package.json
Labels: npm-package

#5056 fix endpoint mocked cache tests
  services/endpoint/endpoint.tester.js
Labels: keep-service-tests-green

#5059 remove git add from lint-staged action
  package.json
Labels: developer-experience, squash when passing

#5058 bump to node 10 for self-hosting users
  Dockerfile
Labels: self-hosting, squash when passing

#5099 resolve some vulnerability warnings
  package-lock.json
Labels: dependencies, squash when passing

#5100 security policy 🔒
  SECURITY.md
Labels: documentation

#5105 update [discord] domain
  services/discord/discord.service.js
  services/discord/discord.tester.js
Labels: service-badge

#5128 fix [githubpullrequestcheckstate] service test
  services/github/github-pull-request-check-state.tester.js
Labels: keep-service-tests-green, squash when passing

#5136 fix docs paths in dangerfile
  dangerfile.js
Labels: developer-experience

#5139 Fix invalid Cache-Control header, run [Endpoint]
  core/base-service/cache-headers.js
  core/base-service/cache-headers.spec.js
  core/base-service/legacy-request-handler.spec.js
  services/endpoint/endpoint.tester.js
Labels: core
