Repository badges/shields, pull requests merged in 2021-01, with the labels that each got.

#6010 use new [HexPM] latest_stable_version property
  services/hexpm/hexpm.service.js
  services/hexpm/hexpm.tester.js
Labels: service-badge, squash when passing

#6000 [PyPI] Fixes Python versions order by using proper Semver comparison
  services/pypi/pypi-python-versions.service.js
  services/pypi/pypi-python-versions.spec.js
Labels: service-badge, squash when passing

#6009 add docs on input validation
  doc/TUTORIAL.md
  doc/input-validation.md
Labels: documentation

#6018 improve [pypi] license parsing from classifiers
  services/pypi/pypi-helpers.js
  services/pypi/pypi-helpers.spec.js
Labels: squash when passing

#6039 add note to docs about img.shields.io vs shields.io
  doc/production-hosting.md
Labels: documentation

#6067 remove erroneous clearRequestCache call, run [DynamicJson]
  core/server/server.js
Labels: core, squash when passing

#6052 Update self-hosting.md documentation for running with Prometheus
  doc/self-hosting.md
Labels: documentation, squash when passing

#6072 fix [wordpress] 'Can't generate version color for false'
  services/wordpress/wordpress-platform.service.js
  services/wordpress/wordpress-platform.tester.js
Labels: bug, service-badge, squash when passing

#6069 add a github action to create tags from labelled PR
  .github/workflows/tag-release.yml
Labels: operations, self-hosting, squash when passing

#6073 Start a changelog, create a tag
  CHANGELOG.md
Labels: release

#6080 link to SimpleIcons update schedule on 'new issue' page
  .github/ISSUE_TEMPLATE/config.yml
Labels: developer-experience, squash when passing

#6075 improve debug output for API calls with query strings
  core/base-service/base.js
  core/base-service/base.spec.js
Labels: developer-experience, squash when passing

#6100 bump approve bot
  .github/workflows/auto-approve.yml
Labels: dependencies

#6108 fix [GitHubIssues] service test
  services/github/github-issues.tester.js
Labels: keep-service-tests-green, squash when passing

#6109 fix [GitHubLerna] service test
  services/github/github-lerna-json.tester.js
Labels: keep-service-tests-green, squash when passing

#6076 [Bitbucket] Server Adding Auth Tokens and Resolving Pull Request api …
  core/server/server.js
Labels: service-badge, squash when passing

#6102 add a GH action to generate a changelog and submit a release PR
  .github/actions/draft-release/Dockerfile
  .github/actions/draft-release/action.yml
  .github/actions/draft-release/entrypoint.sh
  .github/workflows/draft-release.yml
Labels: self-hosting

#6101 Fix [feedz] service in case the registrations page gets paginated
  services/feedz/feedz.service.js
  services/feedz/feedz.service.spec.js
  services/feedz/feedz.tester.js
Labels: service-badge

#6103 convert approve-bot to local action
  .dependabot/config.yml
  .eslintignore
  .github/actions/approve-bot/action.yml
  .github/actions/approve-bot/helpers.js
  .github/actions/approve-bot/index.js
  .github/actions/approve-bot/package-lock.json
  .github/actions/approve-bot/package.json
  .github/workflows/auto-approve.yml
Labels: developer-experience

#6098 Docs.rs badge, run [Docsrs]
  services/docsrs/docsrs.service.js
  services/docsrs/docsrs.tester.js
Labels: service-badge, squash when passing
