Repository badges/shields, pull requests merged in 2023-01, with the labels that each got.

#8771 deprecate [lgtm]
  README.md
  frontend/pages/community.tsx
  services/lgtm/lgtm-alerts.service.js
  services/lgtm/lgtm-alerts.tester.js
  services/lgtm/lgtm-base.js
  services/lgtm/lgtm-grade.service.js
  services/lgtm/lgtm-grade.tester.js
  services/lgtm/lgtm-redirector.tester.js
  services/lgtm/lgtm-test-helpers.js
Labels: service-badge, squash when passing

#8766 Docstrings for php-version service
  core/base-service/resource-cache.js
  services/php-version.js
Labels: service-badge, squash when passing

#8773 deprecate [apm] service
  services/apm/apm.service.js
  services/apm/apm.tester.js
Labels: service-badge, squash when passing

#8477 migrate danger CI job to GHA
  .circleci/config.yml
  .github/workflows/danger.yml
Labels: developer-experience

#8787 Add docstrings for pipenv helpers
  services/pipenv-helpers.js
Labels: documentation

#8786 fix service tests on windows; run [crates] (to prove service tests still run)
  core/base-service/loader.js
  core/base-service/loader.spec.js
Labels: bug, developer-experience, core, squash when passing

#8797 update [githubpipenv] tests/examples
  services/github/github-pipenv.service.js
  services/github/github-pipenv.tester.js
Labels: keep-service-tests-green, squash when passing

#8815 remove danger-plugin-no-test-shortcuts
  dangerfile.js
  package-lock.json
  package.json
Labels: bug, developer-experience, squash when passing

#8421 migrate service tests to GH actions
  .circleci/config.yml
  .github/actions/service-tests/action.yml
  .github/workflows/test-services-17.yml
  .github/workflows/test-services.yml
  core/service-test-runner/infer-pull-request.js
  core/service-test-runner/infer-pull-request.spec.js
  core/service-test-runner/pull-request-services-cli.js
  scripts/mocha2md.js
  services/github/gist/github-gist-last-commit-redirect.tester.js
  services/github/gist/github-gist-last-commit.service.js
  services/github/gist/github-gist-stars-redirect.tester.js
  services/github/gist/github-gist-stars.service.js
Labels: developer-experience

#8823 add a note about fine-grained PATs in the docs
  doc/server-secrets.md
Labels: documentation, squash when passing

#8842 replace [twitter] badge with static fallback
  services/twitter/twitter.service.js
  services/twitter/twitter.tester.js
Labels: service-badge, squash when passing

#8862 build docker images with buildkit v0.9.1
  .github/workflows/build-docker-image.yml
  .github/workflows/create-release.yml
  .github/workflows/publish-docker-next.yml
Labels: operations

#8839 Add ESLint checks for IcedFrisby exclusive/skipped tests
  .eslintrc.yml
  package-lock.json
  package.json
Labels: developer-experience, squash when passing

#8866 skip danger on repo ranger commits
  .github/workflows/danger.yml
Labels: developer-experience, squash when passing
