Repository badges/shields, pull requests merged in 2023-04, with the labels that each got.

#9054 Update the hint of simple-icons
  frontend/components/usage.tsx
Labels: documentation, squash when passing

#9068 fix markdown summary if there are pending tests; run [amo youtube]
  scripts/mocha2md.js
Labels: developer-experience

#8966 Export OpenAPI definitions from service examples; affects [dynamic endpoint static]
  .gitignore
  core/base-service/base.js
  core/base-service/examples.js
  core/base-service/openapi.js
  core/base-service/openapi.spec.js
  core/base-service/service-definitions.js
  frontend/categories/.gitkeep
  scripts/export-openapi-cli.js
  scripts/export-service-definitions-cli.js
  services/dynamic/dynamic-json.service.js
  services/dynamic/dynamic-xml.service.js
  services/dynamic/dynamic-yaml.service.js
  services/endpoint/endpoint.service.js
  services/static-badge/static-badge.service.js
Labels: frontend, blocker

#9081 [crates] Use `?include=` to reduce crates.io backend load
  services/crates/crates-base.js
  services/crates/crates-downloads.tester.js
Labels: service-badge, squash when passing

#9072 remove pull_request:edited trigger from most workflows
  .github/workflows/danger.yml
  .github/workflows/enforce-dependency-review.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-frontend.yml
  .github/workflows/test-integration-17.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-lint.yml
  .github/workflows/test-main-17.yml
  .github/workflows/test-main.yml
  .github/workflows/test-package-cli.yml
  .github/workflows/test-package-lib.yml
Labels: developer-experience

#9065 remove redis token persistence backend
  .github/workflows/test-integration-17.yml
  .github/workflows/test-integration.yml
  CONTRIBUTING.md
  config/local-shields-io-production.template.yml
  core/token-pooling/redis-token-persistence.integration.js
  core/token-pooling/redis-token-persistence.js
  package-lock.json
  package.json
  scripts/redis-connectivity-test.js
  server.js
  services/github/github-constellation.js
Labels: self-hosting

#9069 add fly.io PR review apps
  .dockerignore
  .github/scripts/cleanup-review-apps.sh
  .github/scripts/deploy-review-app.sh
  .github/workflows/cleanup-review-apps.yml
  .github/workflows/deploy-review-app.yml
  fly.toml
Labels: operations, developer-experience, squash when passing

#9078 [SourceForge] Added badges for SourceForge
  services/sourceforge/sourceforge-base.js
  services/sourceforge/sourceforge-commit-count.service.js
  services/sourceforge/sourceforge-commit-count.tester.js
  services/sourceforge/sourceforge-contributors.service.js
  services/sourceforge/sourceforge-contributors.tester.js
  services/sourceforge/sourceforge-downloads.service.js
  services/sourceforge/sourceforge-downloads.tester.js
  services/sourceforge/sourceforge-languages.service.js
  services/sourceforge/sourceforge-languages.tester.js
  services/sourceforge/sourceforge-last-commit.service.js
  services/sourceforge/sourceforge-last-commit.tester.js
  services/sourceforge/sourceforge-platform.service.js
  services/sourceforge/sourceforge-platform.tester.js
  services/sourceforge/sourceforge-translations.service.js
  services/sourceforge/sourceforge-translations.tester.js
Labels: service-badge, squash when passing

#9102 fix [sourceforge] downloads
  services/sourceforge/sourceforge-downloads.service.js
Labels: bug, service-badge
