Repository badges/shields, pull requests merged in 2023-02, with the labels that each got.

#8889 expose port 443 in Dockerfile
  Dockerfile
Labels: operations

#8887 documentation html fixes
  services/github/github-hacktoberfest.service.js
  services/mastodon/mastodon-follow.service.js
  services/matrix/matrix.service.js
  services/mozilla-observatory/mozilla-observatory.service.js
  services/nexus/nexus.service.js
  services/ore/ore-base.js
  services/packagist/packagist-base.js
  services/security-headers/security-headers.service.js
  services/snyk/snyk-vulnerability-github.service.js
  services/steam/steam-workshop.service.js
  services/w3c/w3c-validation-helper.js
  services/wikiapiary/wikiapiary-installs.service.js
Labels: frontend, documentation, squash when passing

#8925 pin 'deploy docs' build to node 16
  .github/workflows/deploy-docs.yml
Labels: developer-experience, squash when passing

#8908 fix: Set uid/gid in docker image to 0
  Dockerfile
Labels: self-hosting, squash when passing

#8923 Add [Vcpkg] version service
  services/vcpkg/vcpkg-version.service.js
  services/vcpkg/vcpkg-version.tester.js
Labels: service-badge, squash when passing

#8927 don't autofocus search
  frontend/components/search.tsx
Labels: frontend

#8922 migrate token pooling to postgres
  .github/actions/integration-tests/action.yml
  .github/workflows/test-integration-17.yml
  .github/workflows/test-integration.yml
  .gitignore
  config/custom-environment-variables.yml
  core/server/server.js
  core/token-pooling/redis-token-persistence.integration.js
  core/token-pooling/sql-token-persistence.integration.js
  core/token-pooling/sql-token-persistence.js
  migrations/1676731511125_initialize.cjs
  package-lock.json
  package.json
  scripts/migrate-token-pool.js
  scripts/write-migrations-config.js
  server.js
  services/github/github-constellation.js
Labels: operations

#8930 fix TypeError: console.warning is not a function
  server.js
Labels: bug

#8687 use `max_stable_version` in rust [crates] badge
  services/crates/crates-version.service.js
  services/crates/crates-version.spec.js
Labels: service-badge, squash when passing

#8931 remove migrate-token-pool.js
  scripts/migrate-token-pool.js
Labels: operations, squash when passing
