Repository badges/shields, pull requests merged in 2025-03, with the labels that each got.

#10918 use SVG2 hrefs
  __snapshots__/make-badge.spec.mjs.js
  badge-maker/CHANGELOG.md
  badge-maker/lib/badge-renderers.js
  core/server/server.spec.js
Labels: core, npm-package

#10919 tweak default cache lengths by category
  core/base-service/base.js
Labels: core

#10924 nodemon watch yml conf files and ignore .github
  package.json
Labels: developer-experience

#10934 update security policy: clarify we don't pay bounties
  SECURITY.md
Labels: documentation

#10935 [sourceforge] add repo param to last commit service
  services/sourceforge/sourceforge-last-commit-redirect.service.js
  services/sourceforge/sourceforge-last-commit-redirect.tester.js
  services/sourceforge/sourceforge-last-commit.service.js
  services/sourceforge/sourceforge-last-commit.tester.js
Labels: service-badge

#10937 build: creates a devcontainer configuration for contributors
  .devcontainer/devcontainer.json
  README.md
Labels: developer-experience

#10938 feat: add new badges for new [ansible] collection APIs
  services/ansible/ansible-collection-downloads.service.js
  services/ansible/ansible-collection-downloads.tester.js
  services/ansible/ansible-collection-version.service.js
  services/ansible/ansible-collection-version.tester.js
  services/ansible/ansible-collection.tester.js
Labels: service-badge

#10956 Ignore package.json files in eslint
  eslint.config.js
Labels: developer-experience

#10954 Update [SourceForge] commit count badge to support repository parameter
  services/sourceforge/sourceforge-commit-count-redirect.service.js
  services/sourceforge/sourceforge-commit-count-redirect.tester.js
  services/sourceforge/sourceforge-commit-count.service.js
  services/sourceforge/sourceforge-commit-count.tester.js
Labels: service-badge

#10958 graceful shutdown
  server.js
Labels: operations, self-hosting

#10957 docker: cleanup some building
  .dockerignore
  Dockerfile
Labels: operations, self-hosting
